In [2]:
import pandas as pd

In [3]:
# 01_Getting_&_Knowing_Your_Data

In [4]:
# World Food Facts

In [5]:
data = pd.read_table('/kaggle/input/world-food-facts/en.openfoodfacts.org.products.tsv')

/tmp/ipykernel_47/428271927.py:1: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_table('/kaggle/input/world-food-facts/en.openfoodfacts.org.products.tsv')

In [6]:
# See the first 5 entries
print(data.head())

    code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...
1   4530  http://world-en.openfoodfacts.org/product/0000...
2   4559  http://world-en.openfoodfacts.org/product/0000...
3  16087  http://world-en.openfoodfacts.org/product/0000...
4  16094  http://world-en.openfoodfacts.org/product/0000...

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de bl√© noir
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)
2      1489069957   2017-03-09T14:32:37Z                         Peanuts
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta

  generic_name quantity  ... fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...                         NaN
1          NaN      NaN  ...                         NaN
2          NaN      NaN  ...                         NaN
3          NaN      NaN  ...                         NaN
4          NaN      NaN  ...                         NaN

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN
1                                  NaN                              NaN
2                                  NaN                              NaN
3                                  NaN                              NaN
4                                  NaN                              NaN

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN
1        NaN             NaN                   NaN                    14.0
2        NaN             NaN                   NaN                     0.0
3        NaN             NaN                   NaN                    12.0
4        NaN             NaN                   NaN                     NaN

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g
0                     NaN                 NaN                 NaN
1                    14.0                 NaN                 NaN
2                     0.0                 NaN                 NaN
3                    12.0                 NaN                 NaN
4                     NaN                 NaN                 NaN

[5 rows x 163 columns]

In [7]:
# What is the number of observations in the dataset?
num_observations = len(data) 
print(num_observations)

356027

In [8]:
# What is the number of columns in the dataset?
num_columns = data.shape[1] 
print(num_columns)

163

In [9]:
#Print the name of all the columns
print(data.columns)

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

In [10]:
# What is the name of 105th column?
column_name_105 = data.columns[104] 
print(column_name_105)

-glucose_100g

In [11]:
# What is the type of the observations of the 105th column?
column_105_type = data.dtypes[104]
print(column_105_type)

float64

In [12]:
# How is the dataset indexed?
print(data.index)

RangeIndex(start=0, stop=356027, step=1)

In [13]:
# What is the product name of the 19th observation?
product_name = data.loc[18,'product_name'] 
print(product_name)

Lotus Organic Brown Jasmine Rice

In [14]:
# New Project

In [15]:
# Occupation
users_df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")

In [16]:
# See the first 25 entries
print(users_df.head(25))

   user_id|age|gender|occupation|zip_code
0                 1|24|M|technician|85711
1                      2|53|F|other|94043
2                     3|23|M|writer|32067
3                 4|24|M|technician|43537
4                      5|33|F|other|15213
5                  6|42|M|executive|98101
6              7|57|M|administrator|91344
7              8|36|M|administrator|05201
8                    9|29|M|student|01002
9                    10|53|M|lawyer|90703
10                    11|39|F|other|30329
11                    12|28|F|other|06405
12                 13|47|M|educator|29206
13                14|45|M|scientist|55106
14                 15|49|F|educator|97301
15            16|21|M|entertainment|10309
16               17|30|M|programmer|06355
17                    18|35|F|other|37212
18                19|40|M|librarian|02138
19                20|42|F|homemaker|95660
20                   21|26|M|writer|30068
21                   22|25|M|writer|40206
22                   23|30|F|artist|48197
23                   24|21|F|artist|94533
24                 25|39|M|engineer|55107

In [17]:
# See the last 10 entries
print(users_df.tail(10))

    user_id|age|gender|occupation|zip_code
933                934|61|M|engineer|22902
934                  935|42|M|doctor|66221
935                   936|24|M|other|32789
936                937|48|M|educator|98072
937              938|38|F|technician|55038
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

In [18]:
# What is the number of observations in the dataset?
num_observations = len(users_df) 
print(num_observations)

943

In [19]:
# What is the number of columns in the dataset?
number_of_columns = users_df.shape[1]
print(number_of_columns)

1

In [20]:
# Print the name of all the columns
print(users_df.columns)

Index(['user_id|age|gender|occupation|zip_code'], dtype='object')

In [21]:
# How is the dataset indexed?
print(users_df.index)

RangeIndex(start=0, stop=943, step=1)

In [22]:
# What is the data type of each column?
print(users_df.dtypes)

user_id|age|gender|occupation|zip_code    object
dtype: object

In [23]:
# Print only the occupation column
# print(users_df['occupation'])  it will caues error becuase dataframe is containig of only 1 column

In [24]:
# How many different occupations are in this dataset?
# print(users_df['occupation'].nunique())

In [25]:
# What is the most frequent occupation?
# print(users_df['occupation'].value_counts().idxmax())

In [26]:
# Summarize the DataFrame
print(users_df.describe())

       user_id|age|gender|occupation|zip_code
count                                     943
unique                                    943
top                   1|24|M|technician|85711
freq                                        1

In [27]:
# New Project

In [28]:
# Chipotle
chipo = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv")

In [29]:
# See the first 10 entries
print(chipo.head(10))

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl
6         3         1                          Side of Chips
7         4         1                          Steak Burrito
8         4         1                       Steak Soft Tacos
9         5         1                          Steak Burrito

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
6                                                NaN     $1.69
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [30]:
# What is the number of observations in the dataset?
print(len(chipo))

4622

In [31]:
# What is the number of columns in the dataset?
print(chipo.shape[1])

5

In [32]:
# What is the number of columns in the dataset?
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [33]:
# How is the dataset indexed?
print(chipo.index)

RangeIndex(start=0, stop=4622, step=1)

In [34]:
# Which was the most-ordered item? 
most_ordered_item = chipo['item_name'].value_counts().idxmax()
print(most_ordered_item)

Chicken Bowl

In [35]:
# For the most-ordered item, how many items were ordered?
item_counts = chipo['item_name'].value_counts()
quantity_ordered = item_counts.max()
print(quantity_ordered)

726

In [36]:
# What was the most ordered item in the choice_description column?
print(chipo['choice_description'].value_counts().idxmax())

[Diet Coke]

In [37]:
# How many items were orderd in total?
print(len(chipo['item_name']))

4622

In [38]:
# Turn the item price into a float
chipo['item_price'] = chipo['item_price'].str[1:].astype(float)

In [39]:
# Check the item price type
print(chipo['item_price'].dtypes)

float64

In [40]:
# Create a lambda function and change the type of item price
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x))

In [41]:
# Check the item price type
print(chipo['item_price'].dtypes)

float64

In [52]:
# How much was the revenue for the period in the dataset?
chipo['revenue'] = chipo['item_price'] * chipo['item_price']
print("{:.3f}".format(chipo['revenue'].sum()))

340813.176

In [43]:
# How many orders were made in the period?
print(chipo['order_id'].nunique())

1834

In [49]:
# What is the average revenue amount per order?
average_revenue_per_order = chipo['revenue'].sum() / chipo['order_id'].nunique()
print("{:.3f}".format(average_revenue_per_order))

185.831

In [55]:
# How many different items are sold?
print(chipo['item_name'].unique())

['Chips and Fresh Tomato Salsa' 'Izze' 'Nantucket Nectar'
 'Chips and Tomatillo-Green Chili Salsa' 'Chicken Bowl' 'Side of Chips'
 'Steak Burrito' 'Steak Soft Tacos' 'Chips and Guacamole'
 'Chicken Crispy Tacos' 'Chicken Soft Tacos' 'Chicken Burrito'
 'Canned Soda' 'Barbacoa Burrito' 'Carnitas Burrito' 'Carnitas Bowl'
 'Bottled Water' 'Chips and Tomatillo Green Chili Salsa' 'Barbacoa Bowl'
 'Chips' 'Chicken Salad Bowl' 'Steak Bowl' 'Barbacoa Soft Tacos'
 'Veggie Burrito' 'Veggie Bowl' 'Steak Crispy Tacos'
 'Chips and Tomatillo Red Chili Salsa' 'Barbacoa Crispy Tacos'
 'Veggie Salad Bowl' 'Chips and Roasted Chili-Corn Salsa'
 'Chips and Roasted Chili Corn Salsa' 'Carnitas Soft Tacos'
 'Chicken Salad' 'Canned Soft Drink' 'Steak Salad Bowl'
 '6 Pack Soft Drink' 'Chips and Tomatillo-Red Chili Salsa' 'Bowl'
 'Burrito' 'Crispy Tacos' 'Carnitas Crispy Tacos' 'Steak Salad'
 'Chips and Mild Fresh Tomato Salsa' 'Veggie Soft Tacos'
 'Carnitas Salad Bowl' 'Barbacoa Salad Bowl' 'Salad' 'Veggie Crispy Tacos'
 'Veggie Salad' 'Carnitas Salad']

In [46]:
# 02_Filtering_&_Sorting